import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import { ResponseType } from "@/typings";
import CurrentCard from "@/components/current/CurrentCard";

export default function Home() {
  const API_KEY = process.env.NEXT_PUBLIC_WEATHER_API_KEY;
  const [response, setResponse] = useState<ResponseType | null>(null);

  const options = {
    method: "GET",
    url: "https://weatherapi-com.p.rapidapi.com/forecast.json",
    params: { q: "Novi Sad", days: "3" },
    headers: {
      "X-RapidAPI-Key": API_KEY,
      "X-RapidAPI-Host": "weatherapi-com.p.rapidapi.com",
    },
  };

  useEffect(() => {
    axios
      .request(options)
      .then(function (response) {
        setResponse(response.data);
      })
      .catch(function (error) {
        console.error(error);
      });
  }, []);

  const [selectedOption, setSelectedOption] = useState("current");

  function handleOptionChange(event: any) {
    setSelectedOption(event.target.value);
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center space-y-10 ">
        <h1 className="text-6xl">WEATHER APP</h1>
        <select value={selectedOption} onChange={handleOptionChange}>
          <option value="current">Current</option>
          <option value="day">Daily</option>
          <option value="hour">Hourly</option>
        </select>

        {selectedOption === "current"
          ? response && <CurrentCard response={response} />
          : null}
      </main>
    </>
  );
}
