import Head from "next/head";
import axios from "axios";
import { useEffect, useState } from "react";
import HomeCard from "@/components/HomeCard";
import { ResponseType } from "@/typings";

export default function Home() {
  const API_KEY = process.env.NEXT_PUBLIC_WEATHER_API_KEY;
  const [response, setResponse] = useState<ResponseType | null>(null);

  const options = {
    method: "GET",
    url: "https://weatherapi-com.p.rapidapi.com/forecast.json",
    params: { q: "Novi Sad", days: "3" },
    headers: {
      "X-RapidAPI-Key": API_KEY,
      "X-RapidAPI-Host": "weatherapi-com.p.rapidapi.com",
    },
  };

  useEffect(() => {
    axios
      .request(options)
      .then(function (response) {
        setResponse(response.data);
      })
      .catch(function (error) {
        console.error(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>WEATHER APP</h1>

        <div>
          <HomeCard response={response} />
        </div>
      </main>
    </>
  );
}
